# Generated by Django 5.2 on 2025-04-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habbits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(max_length=255)),
                (
                    "is_pleasant_habit",
                    models.BooleanField(blank=True, null=True),
                ),
                ("periodicity", models.IntegerField(blank=True, null=True)),
                (
                    "award",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_to_do", models.IntegerField(default=120)),
                ("is_public", models.BooleanField(blank=True, null=True)),
                (
                    "connected_hubbit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="atomicshabbits.habbits",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habbits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
